export const img = {
  GithubIcon: require("./github.png"),
  LinkedIn: require("./linkedin.png"),
  Instagram: require("./instagram.png"),
  Vector1: require("./Vector1.png"),
  Vector2: require("./Vector2.png"),
  Boy: require("./boy.png"),
  ThumbUp: require("./thumbup.png"),
  Crown: require("./crown.png"),
  Glassesimoji: require("./glassesimoji.png"),
  HeartEmoji: require("./heartemoji.png"),
  Glasses: require("./glasses.png"),
  Humble: require("./humble.png"),
  Upwork: require("./Upwork.png"),
  Fiverr: require("./fiverr.png"),
  Amazon: require("./amazon.png"),
  Shopify: require("./Shopify.png"),
  Facebook: require("./Facebook.png"),
  Sidebar: require("./sidebar.png"),
  Ecommerce: require("./ecommerce.png"),
  HOC: require("./hoc.png"),
  MusicApp: require("./musicapp.png"),
  ProfilePic1: require("./profile1.jpg"),
  ProfilePic2: require("./profile2.jpg"),
  ProfilePic3: require("./profile3.jpg"),
  ProfilePic4: require("./profile4.jpg"),
  Wave: require("./wave.png"),
};
